modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="jj2096_surface_compat"
version="${version}"
displayName="JJ2096 TerraBlender Surface Compatibility"
authors="Misaka2002"
description='''Preserves marked JJ2096 pack surface defaults while retaining TerraBlender namespace rules.'''

[[dependencies.jj2096_surface_compat]]
modId="neoforge"
type="required"
versionRange="[21.1.251]"
ordering="NONE"
side="BOTH"

[[dependencies.jj2096_surface_compat]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.jj2096_surface_compat]]
modId="terrablender"
type="required"
versionRange="[4.1.0.8]"
ordering="AFTER"
side="BOTH"
